version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: "Dataset raw__date"
    tables:
      - name: product
        identifier: raw_gz_product
        description: "table product"
        columns:
          - name: products_id
            description: "ID des produits"
            tests:
              - not_null
              - unique
          - name: purchase_price
            description: "prix d'achat de chaque produit"
      - name: sales
        identifier: raw_gz_sales
        description: "table sales"
        # Freshness testing - make sure to fill in the ...
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after:
            count: 90
            period: day
        columns:
          - name: orders_id
            description: "ID des commandes"
          - name: date_date
            description: "date de la commande"
          - name: products_id
            description: "ID des produits"
          - name: revenue
            description: "revenue par produit"
          - name: quantity
            description: "quantité de produits vendu dans la commande"
        tests:
          - unique:
              column_name: "(orders_id|| '-' || pdt_id)"
      - name: ship
        identifier: raw_gz_ship
        description: "table ship"
        columns:
          - name: orders_id
            description: "ID des commandes"
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: "shipping_fee"
          - name: logcost
            description: "coût de la logistique"
          - name: ship_cost
            description: "coût de la livraison"
      - name: adwords
        identifier: raw_gz_adwords
        columns:
          - name: date_date
            description: "date"
          - name: paid_source
            description: "source de paiement"
          - name: campaign_key
            description: "clé de campagne"
          - name: camPGN_name
            description: "nom de campagne"
          - name: ads_cost
            description: "coût de la pub"
          - name: impression
            description: "nombre d'impression"
          - name: click
            description: "nombre de click"
        tests:
          - unique:
              column_name: "(date_date|| '-' || campaign_key)"
      - name: bing
        identifier: raw_gz_bing
        columns:
          - name: date_date
            description: "date"
          - name: paid_source
            description: "source de paiement"
          - name: campaign_key
            description: "clé de campagne"
          - name: camPGN_name
            description: "nom de campagne"
          - name: ads_cost
            description: "coût de la pub"
          - name: impression
            description: "nombre d'impression"
          - name: click
            description: "nombre de click"
        tests:
          - unique:
              column_name: "(date_date|| '-' || campaign_key)"
      - name: criteo
        identifier: raw_gz_criteo
        columns:
          - name: date_date
            description: "date"
          - name: paid_source
            description: "source de paiement"
          - name: campaign_key
            description: "clé de campagne"
          - name: camPGN_name
            description: "nom de campagne"
          - name: ads_cost
            description: "coût de la pub"
          - name: impression
            description: "nombre d'impression"
          - name: click
            description: "nombre de click"
        tests:
          - unique:
              column_name: "(date_date|| '-' || campaign_key)"
      - name: facebook
        identifier: raw_gz_facebook
        columns:
          - name: date_date
            description: "date"
          - name: paid_source
            description: "source de paiement"
          - name: campaign_key
            description: "clé de campagne"
          - name: camPGN_name
            description: "nom de campagne"
          - name: ads_cost
            description: "coût de la pub"
          - name: impression
            description: "nombre d'impression"
          - name: click
            description: "nombre de click"
        tests:
          - unique:
              column_name: "(date_date|| '-' || campaign_key)"